version: '3.9'

services:
  sso_db:
    container_name: sso_example_db
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"